//! Parity tests against the committed cross-implementation fixture
//! (`tests/fixtures/synthetic_round.json`, generated by Python `tests/gen_fixture.py`
//! on branch feature/3d-replay). The fixture's `b64` is the exact Python-encoded C2R3
//! blob: decoding it must reproduce Python's decode within the quantization tolerances,
//! and re-encoding the same deterministic model must reproduce it byte-for-byte.

use base64::Engine;
use serde_json::{json, Value};

use c2r3::{decode_round, encode_round, PlayerMeta, RoundModel, Track};

const PRESENT: u8 = 0x01;
const ALIVE: u8 = 0x02;
const CROUCH: u8 = 0x04;
const SCOPED: u8 = 0x08;

const N: usize = 24;

fn fixture() -> Value {
    let raw = include_str!("fixtures/synthetic_round.json");
    serde_json::from_str(raw).expect("fixture parses")
}

fn fixture_bytes(fx: &Value) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(fx["b64"].as_str().expect("b64"))
        .expect("b64 decodes")
}

fn circ_deg_diff(a: f64, b: f64) -> f64 {
    ((a - b + 180.0).rem_euclid(360.0) - 180.0).abs()
}

// ---------------------------------------------------------------------------
// Port of tests/gen_fixture.py's deterministic model builder (no RNG).
// ---------------------------------------------------------------------------

fn det_track(seed: usize, alive_from: usize, alive_to: usize) -> Track {
    let s = seed as f64;
    let mut tr = Track {
        x: vec![0.0; N],
        y: vec![0.0; N],
        z: vec![0.0; N],
        yaw: vec![0.0; N],
        pitch: vec![0.0; N],
        flags: vec![0; N],
        health: vec![0; N],
        weapon: vec![255; N],
        flash: vec![0; N],
    };
    let mut last: Option<(f64, f64, f64, f64, f64)> = None;
    for i in 0..N {
        let alive = alive_from <= i && i < alive_to;
        if alive {
            let k = (i - alive_from) as f64;
            tr.x[i] = -1200.0 + s * 300.0 + 14.0 * k;
            tr.y[i] = 900.0 - s * 220.0 - 8.5 * k;
            tr.z[i] = -240.0 + 30.0 * (0.35 * i as f64 + s).sin();
            // deliberately sweep yaw across the +/-180 seam for some seeds
            tr.yaw[i] = (150.0 + s * 40.0 + 7.0 * k + 180.0).rem_euclid(360.0) - 180.0;
            tr.pitch[i] = -3.0 + 4.0 * (0.2 * i as f64).sin();
            let ki = i - alive_from;
            tr.flags[i] = PRESENT
                | ALIVE
                | if ki % 5 == 0 { CROUCH } else { 0 }
                | if seed == 1 && (6..=9).contains(&ki) { SCOPED } else { 0 };
            tr.health[i] = std::cmp::max(1, 100 - 3 * ki as i64) as u8;
            tr.weapon[i] = (1 + seed % 4) as u8;
            tr.flash[i] = if (3..=5).contains(&ki) { 180 } else { 0 };
            last = Some((tr.x[i], tr.y[i], tr.z[i], tr.yaw[i], tr.pitch[i]));
        } else {
            let fx = last.unwrap_or((-1200.0 + s * 300.0, 900.0, -240.0, 150.0, 0.0));
            tr.x[i] = fx.0;
            tr.y[i] = fx.1;
            tr.z[i] = fx.2;
            tr.yaw[i] = fx.3;
            tr.pitch[i] = fx.4;
        }
    }
    tr
}

fn build_model() -> RoundModel {
    let sids = [
        "76561198000000001",
        "76561198000000002",
        "76561198000000003",
    ];
    RoundModel {
        map: "de_mirage".into(),
        round: 7,
        tick_rate: 64,
        sample_stride: 4,
        sample_rate: 16.0,
        n_samples: N,
        start_tick: 5000,
        end_tick: 5000 + N as i64 * 4,
        players: vec![
            PlayerMeta { slot: 0, sid: sids[0].into(), name: "Alpha".into(), team: 2 },
            PlayerMeta { slot: 1, sid: sids[1].into(), name: "Bravo".into(), team: 2 },
            PlayerMeta { slot: 2, sid: sids[2].into(), name: "César⚡".into(), team: 3 },
        ],
        weapon_table: vec!["".into(), "AK".into(), "AWP".into(), "USP".into(), "Deagle".into()],
        // Key order inside these objects is part of the byte format (carried verbatim).
        utility: vec![
            json!({"type": "smoke", "thrower": sids[0], "throwTick": 5040,
                   "detTick": 5080, "throwSample": 10, "detSample": 20,
                   "pos": [123.0, -456.0, -200.0], "radius": 144, "duration": 18.0}),
            json!({"type": "flash", "thrower": sids[2], "detTick": 5060,
                   "detSample": 15, "pos": [200.0, 100.0, -180.0], "radius": 120,
                   "affected": [{"sid": sids[0], "blindDuration": 2.35}]}),
        ],
        tracks: vec![det_track(0, 0, N), det_track(1, 0, 15), det_track(2, 8, N)],
    }
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

#[test]
fn decode_matches_python_decode() {
    let fx = fixture();
    let data = fixture_bytes(&fx);
    assert_eq!(
        data.len() as u64,
        fx["byteLength"].as_u64().unwrap(),
        "fixture byteLength"
    );

    let dec = decode_round(&data).expect("decodes");
    let fh = &fx["header"];

    assert_eq!(dec.map, fh["map"].as_str().unwrap());
    assert_eq!(dec.round, fh["round"].as_i64().unwrap());
    assert_eq!(dec.n_samples as u64, fh["nSamples"].as_u64().unwrap());
    for (i, o) in fh["origin"].as_array().unwrap().iter().enumerate() {
        assert_eq!(dec.origin[i], o.as_f64().unwrap(), "origin[{}] exact", i);
    }
    assert_eq!(dec.scale_xy, fh["scaleXY"].as_f64().unwrap(), "scaleXY exact");
    assert_eq!(dec.scale_z, fh["scaleZ"].as_f64().unwrap(), "scaleZ exact");

    // players / weaponTable / utility metadata parity (deep equality)
    let players: Vec<PlayerMeta> = fh["players"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| PlayerMeta {
            slot: p["slot"].as_i64().unwrap(),
            sid: p["sid"].as_str().unwrap().into(),
            name: p["name"].as_str().unwrap().into(),
            team: p["team"].as_i64().unwrap(),
        })
        .collect();
    assert_eq!(dec.players, players);
    let wt: Vec<String> = fh["weaponTable"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_owned())
        .collect();
    assert_eq!(dec.weapon_table, wt);
    assert_eq!(&Value::Array(dec.utility.clone()), &fh["utility"], "utility verbatim");

    // tracks vs Python decode within quantization tolerances (discrete exact)
    let tol = &fx["tolerances"];
    let (tp, tz, ta, tpi) = (
        tol["pos"].as_f64().unwrap(),
        tol["z"].as_f64().unwrap(),
        tol["ang"].as_f64().unwrap(),
        tol["pitch"].as_f64().unwrap(),
    );
    let exp_tracks = fx["expected"]["tracks"].as_array().unwrap();
    assert_eq!(dec.tracks.len(), exp_tracks.len());
    for (si, (got, exp)) in dec.tracks.iter().zip(exp_tracks).enumerate() {
        let f = |k: &str| -> Vec<f64> {
            exp[k].as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect()
        };
        let d = |k: &str| -> Vec<u8> {
            exp[k].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as u8).collect()
        };
        let (ex, ey, ez, eyaw, epitch) = (f("X"), f("Y"), f("Z"), f("yaw"), f("pitch"));
        for i in 0..N {
            assert!((got.x[i] - ex[i]).abs() <= tp, "p{si} s{i} X {} vs {}", got.x[i], ex[i]);
            assert!((got.y[i] - ey[i]).abs() <= tp, "p{si} s{i} Y {} vs {}", got.y[i], ey[i]);
            assert!((got.z[i] - ez[i]).abs() <= tz, "p{si} s{i} Z {} vs {}", got.z[i], ez[i]);
            assert!(
                circ_deg_diff(got.yaw[i], eyaw[i]) <= ta,
                "p{si} s{i} yaw {} vs {}", got.yaw[i], eyaw[i]
            );
            assert!(
                (got.pitch[i] - epitch[i]).abs() <= tpi,
                "p{si} s{i} pitch {} vs {}", got.pitch[i], epitch[i]
            );
        }
        assert_eq!(got.flags, d("flags"), "p{si} flags");
        assert_eq!(got.health, d("health"), "p{si} health");
        assert_eq!(got.weapon, d("weapon"), "p{si} weapon");
        assert_eq!(got.flash, d("flash"), "p{si} flash");
    }
}

#[test]
fn encode_is_byte_identical_to_python() {
    let fx = fixture();
    let want = fixture_bytes(&fx);
    let (got, clamps) = encode_round(&build_model()).expect("encodes");
    assert_eq!(clamps, 0, "fixture model must not clamp");

    if got != want {
        // Rich diagnostics: locate the first differing byte and say which region it's in.
        let first_diff = got
            .iter()
            .zip(&want)
            .position(|(a, b)| a != b)
            .unwrap_or_else(|| got.len().min(want.len()));
        let want_hlen = u32::from_le_bytes(want[8..12].try_into().unwrap()) as usize;
        let got_hlen = u32::from_le_bytes(got[8..12].try_into().unwrap()) as usize;
        let region = if first_diff < 12 {
            "container preamble"
        } else if first_diff < 12 + want_hlen.min(got_hlen) {
            "JSON header"
        } else {
            "tick-stream blob"
        };
        let ctx = |d: &[u8]| -> String {
            let lo = first_diff.saturating_sub(12);
            let hi = (first_diff + 12).min(d.len());
            d[lo..hi].iter().map(|b| format!("{:02x} ", b)).collect()
        };
        panic!(
            "encoded bytes differ from Python fixture: len {} vs {}, first diff at \
             offset {} ({}); headerLen {} vs {}\n  ours:   {}\n  python: {}\n  our header:    {}\n  python header: {}",
            got.len(),
            want.len(),
            first_diff,
            region,
            got_hlen,
            want_hlen,
            ctx(&got),
            ctx(&want),
            String::from_utf8_lossy(&got[12..12 + got_hlen]),
            String::from_utf8_lossy(&want[12..12 + want_hlen]),
        );
    }
}

/// Decoder-verified equivalence (pre-approved fallback bar, kept as a separate test so
/// it stays meaningful even while byte-identity also holds): our encoder's output must
/// DECODE to the same values as Python's committed bytes, within the fixture tolerances.
#[test]
fn encode_decodes_equivalent_to_python() {
    let fx = fixture();
    let (ours, _) = encode_round(&build_model()).expect("encodes");
    let a = decode_round(&ours).expect("ours decodes");
    let b = decode_round(&fixture_bytes(&fx)).expect("python bytes decode");

    let tol = &fx["tolerances"];
    let (tp, tz, ta, tpi) = (
        tol["pos"].as_f64().unwrap(),
        tol["z"].as_f64().unwrap(),
        tol["ang"].as_f64().unwrap(),
        tol["pitch"].as_f64().unwrap(),
    );
    assert_eq!(a.players, b.players);
    assert_eq!(a.weapon_table, b.weapon_table);
    assert_eq!(a.utility, b.utility);
    for (si, (ta_, tb)) in a.tracks.iter().zip(&b.tracks).enumerate() {
        for i in 0..N {
            assert!((ta_.x[i] - tb.x[i]).abs() <= 2.0 * tp, "p{si} s{i} X");
            assert!((ta_.y[i] - tb.y[i]).abs() <= 2.0 * tp, "p{si} s{i} Y");
            assert!((ta_.z[i] - tb.z[i]).abs() <= 2.0 * tz, "p{si} s{i} Z");
            assert!(circ_deg_diff(ta_.yaw[i], tb.yaw[i]) <= 2.0 * ta, "p{si} s{i} yaw");
            assert!((ta_.pitch[i] - tb.pitch[i]).abs() <= 2.0 * tpi, "p{si} s{i} pitch");
        }
        assert_eq!(ta_.flags, tb.flags);
        assert_eq!(ta_.health, tb.health);
        assert_eq!(ta_.weapon, tb.weapon);
        assert_eq!(ta_.flash, tb.flash);
    }
}
