//! demoReview 3D replay viewer — Bevy/WASM port of the Three.js app generated by
//! build3d_app.py (branch feature/3d-replay). The HTML page owns the UI (scrubber,
//! round selector, speed buttons, labels, timeline markers, flash overlay div);
//! this crate owns the 3D scene and playback clock. See www/index.html for the
//! JS <-> WASM control interface documentation.

mod coords;
mod orbit;
mod scene;
mod state;
mod util;

pub use coords::*;

use bevy::core_pipeline::tonemapping::Tonemapping;
use bevy::prelude::*;
use wasm_bindgen::prelude::*;

use state::{
    ang_lerp, lerp, push_control, sample_pos, ControlMsg, GreyboxTag, PlayerBody, PlayerNose,
    RoundState, UtilTag, Viewer, QUEUE,
};
use util::{tracer_frame, util_frame, UtilKind};

// ---------------------------------------------------------------------------
// JS -> WASM control surface (exported); see www/index.html for the caller side
// ---------------------------------------------------------------------------

/// Start the Bevy app on the given canvas (CSS selector). Returns immediately;
/// all further control goes through the queued messages below.
#[wasm_bindgen]
pub fn run(canvas_selector: String) {
    console_error_panic_hook::set_once();
    App::new()
        .insert_resource(ClearColor(util::hex_color("#0b0e14")))
        .insert_resource(Viewer::default())
        .insert_resource(orbit::OrbitCam::default())
        .insert_resource(LabelsOut::default())
        .insert_resource(TracersOut::default())
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                canvas: Some(canvas_selector),
                fit_canvas_to_parent: true,
                prevent_default_event_handling: false,
                ..default()
            }),
            ..default()
        }))
        .add_systems(Startup, setup)
        .add_systems(
            Update,
            (
                drain_controls,
                advance_clock,
                update_players,
                update_utility,
                draw_grid,
                orbit::orbit_camera,
                report_frame,
            )
                .chain(),
        )
        .run();
}

/// Feed manifest.json's text (greybox + team colors + camera framing).
#[wasm_bindgen]
pub fn load_manifest(json: String) {
    push_control(ControlMsg::LoadManifest(json));
}

/// Feed one round's raw .3dr bytes. Decodes synchronously and returns the round's
/// header JSON (players, weaponTable, utility, nSamples, ...) for the page UI.
#[wasm_bindgen]
pub fn load_round(bytes: &[u8]) -> Result<String, JsValue> {
    let dec = c2r3::decode_round(bytes).map_err(|e| JsValue::from_str(&e.to_string()))?;
    let header = serde_json::to_string(&dec.header).map_err(|e| JsValue::from_str(&e.to_string()))?;
    push_control(ControlMsg::LoadRound(Box::new(dec)));
    Ok(header)
}

#[wasm_bindgen]
pub fn seek(t: f64) {
    push_control(ControlMsg::Seek(t));
}

#[wasm_bindgen]
pub fn set_playing(playing: bool) {
    push_control(ControlMsg::SetPlaying(playing));
}

#[wasm_bindgen]
pub fn set_speed(speed: f64) {
    push_control(ControlMsg::SetSpeed(speed));
}

/// `?flash=<playerName>` deep-link: whose flash channel drives the page overlay.
#[wasm_bindgen]
pub fn set_flash_focus(name: Option<String>) {
    push_control(ControlMsg::SetFlashFocus(name));
}

// ---------------------------------------------------------------------------
// WASM -> JS per-frame report. Flat f32 payload (see index.html for the layout):
// [clock, duration, playing, flashOpacity, nPlayers, nTracers,
//  {x, y, visible} * nPlayers,            (normalized viewport coords)
//  {utilIdx, x, y, opacity} * nTracers]
// ---------------------------------------------------------------------------

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = window, js_name = __replayFrame)]
    fn replay_frame(data: &[f32]);
}

#[cfg(not(target_arch = "wasm32"))]
fn replay_frame(_data: &[f32]) {}

/// Interpolated foot positions from update_players, consumed by report_frame.
#[derive(Resource, Default)]
struct LabelsOut(Vec<(Vec3, bool)>);

/// Tracer label anchors from update_utility: (utility index, tip, opacity).
#[derive(Resource, Default)]
struct TracersOut(Vec<(usize, Vec3, f32)>);

// ---------------------------------------------------------------------------
// systems
// ---------------------------------------------------------------------------

fn setup(mut commands: Commands) {
    commands.spawn((
        Camera3d::default(),
        // match the Three.js PerspectiveCamera(55, ..., 0.1, 4000)
        Projection::from(PerspectiveProjection {
            fov: 55.0_f32.to_radians(),
            near: 0.1,
            far: 4000.0,
            ..default()
        }),
        Tonemapping::None, // Three.js renders with NoToneMapping; keep colors comparable
        // hemisphere-light stand-in (AmbientLight is a per-camera component in 0.19)
        AmbientLight {
            color: Color::srgb_u8(0xbf, 0xd4, 0xff),
            brightness: 420.0,
            ..default()
        },
        Transform::from_xyz(0.0, 58.0, 58.0).looking_at(Vec3::ZERO, Vec3::Y),
    ));
    commands.spawn((
        DirectionalLight {
            illuminance: 4200.0,
            ..default()
        },
        Transform::from_xyz(40.0, 80.0, 20.0).looking_at(Vec3::ZERO, Vec3::Y),
    ));
}

#[allow(clippy::too_many_arguments)]
fn drain_controls(
    mut commands: Commands,
    mut viewer: ResMut<Viewer>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    asset_server: Res<AssetServer>,
    mut orbit_cam: ResMut<orbit::OrbitCam>,
    q_greybox: Query<Entity, With<GreyboxTag>>,
    q_round: Query<Entity, Or<(With<PlayerBody>, With<PlayerNose>, With<UtilTag>)>>,
) {
    let msgs: Vec<ControlMsg> = std::mem::take(&mut *QUEUE.lock().unwrap());
    for msg in msgs {
        match msg {
            ControlMsg::LoadManifest(json) => match scene::parse_manifest(&json) {
                Ok(m) => {
                    for e in &q_greybox {
                        commands.entity(e).despawn();
                    }
                    let center =
                        scene::build_greybox(&mut commands, &mut meshes, &mut materials, &asset_server, &m);
                    orbit_cam.target = center;
                    orbit_cam.yaw = 0.0;
                    orbit_cam.pitch = std::f32::consts::FRAC_PI_4;
                    orbit_cam.dist = 58.0 * std::f32::consts::SQRT_2;
                    viewer.manifest = Some(m);
                }
                Err(e) => warn!("bad manifest: {e}"),
            },
            ControlMsg::LoadRound(dec) => {
                let Some(m) = viewer.manifest.as_ref() else {
                    warn!("load_round before load_manifest; ignoring");
                    continue;
                };
                for e in &q_round {
                    commands.entity(e).despawn();
                }
                scene::spawn_players(&mut commands, &mut meshes, &mut materials, m, &dec);

                let n = dec.n_samples;
                let rate = dec.sample_rate;
                let duration = if n > 1 { (n as f64 - 1.0) / rate } else { 0.0 };
                let utils: Vec<util::UtilItem> = dec
                    .utility
                    .iter()
                    .filter_map(|u| {
                        util::build_util_item(
                            &mut commands,
                            &mut meshes,
                            &mut materials,
                            u,
                            m.scene_scale,
                            rate,
                        )
                    })
                    .collect();

                viewer.flash_focus = resolve_focus(viewer.flash_focus_name.as_deref(), &dec);
                viewer.round = Some(RoundState { dec: *dec, n, rate, duration, utils });
                viewer.clock = 0.0;
            }
            ControlMsg::Seek(t) => {
                let dur = viewer.round.as_ref().map(|r| r.duration).unwrap_or(0.0);
                viewer.clock = t.clamp(0.0, dur);
            }
            ControlMsg::SetPlaying(p) => {
                // replay from the start when resuming at the end (template behavior)
                if p {
                    if let Some(r) = viewer.round.as_ref() {
                        if viewer.clock >= r.duration {
                            viewer.clock = 0.0;
                        }
                    }
                }
                viewer.playing = p;
            }
            ControlMsg::SetSpeed(s) => viewer.speed = s,
            ControlMsg::SetFlashFocus(name) => {
                viewer.flash_focus_name = name;
                viewer.flash_focus = viewer.round.as_ref().and_then(|r| {
                    resolve_focus(viewer.flash_focus_name.as_deref(), &r.dec)
                });
            }
        }
    }
}

fn resolve_focus(name: Option<&str>, dec: &c2r3::DecodedRound) -> Option<usize> {
    let name = name?.to_lowercase();
    dec.players.iter().position(|p| p.name.to_lowercase() == name)
}

fn advance_clock(time: Res<Time>, mut viewer: ResMut<Viewer>) {
    if !viewer.playing {
        return;
    }
    let Some(duration) = viewer.round.as_ref().map(|r| r.duration) else {
        return;
    };
    viewer.clock += time.delta_secs_f64() * viewer.speed;
    if viewer.clock >= duration {
        viewer.clock = duration;
        viewer.playing = false; // auto-pause at round end
    }
}

fn update_players(
    viewer: Res<Viewer>,
    mut labels: ResMut<LabelsOut>,
    mut q_body: Query<(&PlayerBody, &mut Transform, &mut Visibility), Without<PlayerNose>>,
    mut q_nose: Query<(&PlayerNose, &mut Transform, &mut Visibility), Without<PlayerBody>>,
) {
    labels.0.clear();
    let (Some(m), Some(r)) = (viewer.manifest.as_ref(), viewer.round.as_ref()) else {
        return;
    };
    let s_scale = m.scene_scale;
    let (i0, i1, f, _s) = sample_pos(viewer.clock, r.rate, r.n);
    let cap_h = scene::CAP_H;

    // per-slot interpolated pose (computed once, applied to body + nose + label)
    let mut poses: Vec<Option<(Vec3, f32)>> = Vec::with_capacity(r.dec.tracks.len());
    for tr in &r.dec.tracks {
        if r.n == 0 || tr.flags[i0] & c2r3::F_ALIVE == 0 {
            poses.push(None);
            continue;
        }
        // never interpolate into a dead/frozen frame
        let g = if tr.flags[i1] & c2r3::F_ALIVE != 0 { f } else { 0.0 };
        let x = lerp(tr.x[i0], tr.x[i1], g);
        let y = lerp(tr.y[i0], tr.y[i1], g);
        let z = lerp(tr.z[i0], tr.z[i1], g);
        let yaw = ang_lerp(tr.yaw[i0], tr.yaw[i1], g).to_radians() as f32;
        let sc = Vec3::from_array(world_to_scene(x, y, z, s_scale));
        poses.push(Some((sc, yaw)));
    }

    for (body, mut tf, mut vis) in &mut q_body {
        match poses.get(body.slot).copied().flatten() {
            Some((sc, yaw)) => {
                *tf = Transform::from_translation(sc + Vec3::Y * (cap_h / 2.0))
                    .with_rotation(Quat::from_rotation_y(yaw));
                *vis = Visibility::Visible;
            }
            None => *vis = Visibility::Hidden,
        }
    }
    for (nose, mut tf, mut vis) in &mut q_nose {
        match poses.get(nose.slot).copied().flatten() {
            Some((sc, yaw)) => {
                *tf = Transform::from_translation(Vec3::new(
                    sc.x + yaw.cos() * 0.4,
                    sc.y + cap_h * 0.62,
                    sc.z - yaw.sin() * 0.4,
                ))
                .with_rotation(
                    Quat::from_rotation_y(yaw)
                        * Quat::from_rotation_z(-std::f32::consts::FRAC_PI_2),
                );
                *vis = Visibility::Visible;
            }
            None => *vis = Visibility::Hidden,
        }
    }
    for pose in &poses {
        match pose {
            Some((sc, _)) => labels.0.push((*sc + Vec3::Y * (cap_h + 0.8), true)),
            None => labels.0.push((Vec3::ZERO, false)),
        }
    }
}

#[allow(clippy::too_many_arguments)]
fn update_utility(
    viewer: Res<Viewer>,
    mut tracers_out: ResMut<TracersOut>,
    mut materials: ResMut<Assets<StandardMaterial>>,
    q_mat: Query<&MeshMaterial3d<StandardMaterial>>,
    mut q_tf: Query<&mut Transform>,
    mut q_vis: Query<&mut Visibility>,
    mut gizmos: Gizmos,
) {
    tracers_out.0.clear();
    let Some(r) = viewer.round.as_ref() else {
        return;
    };
    let (_i0, _i1, _f, s) = sample_pos(viewer.clock, r.rate, r.n);
    let tsec = viewer.clock;

    let set_vis = |q: &mut Query<&mut Visibility>, e: Entity, on: bool| {
        if let Ok(mut v) = q.get_mut(e) {
            *v = if on { Visibility::Visible } else { Visibility::Hidden };
        }
    };
    let set_alpha = |mats: &mut Assets<StandardMaterial>,
                         q: &Query<&MeshMaterial3d<StandardMaterial>>,
                         e: Entity,
                         a: f32| {
        if let Ok(handle) = q.get(e) {
            if let Some(mut mat) = mats.get_mut(&handle.0) {
                let mut c = mat.base_color;
                c.set_alpha(a);
                mat.base_color = c;
            }
        }
    };

    for (idx, item) in r.utils.iter().enumerate() {
        if let Some(tr) = &item.tracer {
            if let Some((count, op, tip)) = tracer_frame(tr, s) {
                gizmos.linestrip(
                    tr.pts[..count.min(tr.pts.len())].iter().copied(),
                    tr.color.with_alpha(op),
                );
                if op > 0.06 {
                    tracers_out.0.push((idx, tip + Vec3::Y * 0.6, op));
                }
            }
        }
        let frame = util_frame(item, s);
        let p = frame.p;
        match &item.kind {
            UtilKind::Smoke { mesh, grow } => {
                if !frame.in_window {
                    set_vis(&mut q_vis, *mesh, false);
                    continue;
                }
                let growf = ((s - item.s0) / grow).min(1.0);
                let fade = if p > 0.9 { (1.0 - p) / 0.1 } else { 1.0 };
                set_vis(&mut q_vis, *mesh, true);
                if let Ok(mut tf) = q_tf.get_mut(*mesh) {
                    tf.scale = Vec3::splat(item.r_s * growf as f32);
                }
                set_alpha(&mut materials, &q_mat, *mesh, (0.34 * growf.min(fade)) as f32);
            }
            UtilKind::Molotov { disc, flames } => {
                if !frame.in_window {
                    set_vis(&mut q_vis, *disc, false);
                    for fl in flames {
                        set_vis(&mut q_vis, *fl, false);
                    }
                    continue;
                }
                let growf = ((s - item.s0) / ((item.s1 - item.s0) * 0.06).max(1.0)).min(1.0);
                let fade = if p > 0.85 { (1.0 - p) / 0.15 } else { 1.0 };
                set_vis(&mut q_vis, *disc, true);
                set_alpha(&mut materials, &q_mat, *disc, (0.42 * fade * growf) as f32);
                for (k, fl) in flames.iter().enumerate() {
                    set_vis(&mut q_vis, *fl, true);
                    let flicker = 0.55 + 0.45 * (tsec * 10.0 + k as f64 * 1.7).sin();
                    if let Ok(mut tf) = q_tf.get_mut(*fl) {
                        tf.scale = Vec3::new(1.0, (flicker * 1.7) as f32, 1.0);
                    }
                    set_alpha(&mut materials, &q_mat, *fl, (0.5 * fade * growf * flicker) as f32);
                }
            }
            UtilKind::Burst { mesh, scale, base } => {
                if !frame.in_window {
                    set_vis(&mut q_vis, *mesh, false);
                    continue;
                }
                set_vis(&mut q_vis, *mesh, true);
                if let Ok(mut tf) = q_tf.get_mut(*mesh) {
                    tf.scale = Vec3::splat(scale * (0.3 + p as f32));
                }
                set_alpha(&mut materials, &q_mat, *mesh, (1.0 - p as f32) * base);
            }
            UtilKind::Decoy { mesh } => {
                if !frame.in_window {
                    set_vis(&mut q_vis, *mesh, false);
                    continue;
                }
                set_vis(&mut q_vis, *mesh, true);
                set_alpha(&mut materials, &q_mat, *mesh, (0.22 + 0.14 * (tsec * 6.0).sin()) as f32);
            }
        }
    }
}

/// GridHelper equivalent: 40 divisions over the radar rect, drawn as gizmo lines.
fn draw_grid(viewer: Res<Viewer>, mut gizmos: Gizmos) {
    let Some(m) = viewer.manifest.as_ref() else {
        return;
    };
    let rect = radar_ground_rect(&m.cal, m.scene_scale);
    let y = m.ground_y - 0.015;
    let half = rect.half_x;
    let (cx, cz) = (rect.center[0], rect.center[2]);
    let center_col = util::hex_color("#2a3342");
    let grid_col = util::hex_color("#1b2230");
    for i in 0..=40 {
        let t = -half + half * 2.0 * (i as f32 / 40.0);
        let col = if i == 20 { center_col } else { grid_col };
        gizmos.line(
            Vec3::new(cx + t, y, cz - half),
            Vec3::new(cx + t, y, cz + half),
            col,
        );
        gizmos.line(
            Vec3::new(cx - half, y, cz + t),
            Vec3::new(cx + half, y, cz + t),
            col,
        );
    }
}

fn report_frame(
    viewer: Res<Viewer>,
    labels: Res<LabelsOut>,
    tracers: Res<TracersOut>,
    q_cam: Query<(&Camera, &GlobalTransform), With<Camera3d>>,
) {
    let Ok((cam, cam_tf)) = q_cam.single() else {
        return;
    };
    let viewport = cam.logical_viewport_size().unwrap_or(Vec2::ONE);
    let project = |world: Vec3| -> Option<Vec2> {
        cam.world_to_viewport(cam_tf, world).ok().map(|v| v / viewport)
    };

    let (clock, duration, playing) = (
        viewer.clock,
        viewer.round.as_ref().map(|r| r.duration).unwrap_or(0.0),
        viewer.playing,
    );
    // flash overlay opacity from the focus player's flash channel (raw f, like the JS)
    let flash_opacity = match (viewer.flash_focus, viewer.round.as_ref()) {
        (Some(slot), Some(r)) if r.n > 0 => {
            let (i0, i1, f, _s) = sample_pos(clock, r.rate, r.n);
            let tr = &r.dec.tracks[slot];
            (lerp(tr.flash[i0] as f64, tr.flash[i1] as f64, f) / 255.0).min(1.0) as f32
        }
        _ => 0.0,
    };

    let mut data: Vec<f32> = vec![
        clock as f32,
        duration as f32,
        if playing { 1.0 } else { 0.0 },
        flash_opacity,
        labels.0.len() as f32,
        tracers.0.len() as f32,
    ];
    for (world, visible) in &labels.0 {
        match (visible, project(*world)) {
            (true, Some(v)) => data.extend([v.x, v.y, 1.0]),
            _ => data.extend([0.0, 0.0, 0.0]),
        }
    }
    for (idx, tip, op) in &tracers.0 {
        match project(*tip) {
            Some(v) => data.extend([*idx as f32, v.x, v.y, *op]),
            None => data.extend([*idx as f32, 0.0, 0.0, 0.0]),
        }
    }
    replay_frame(&data);
}
